Fix CUDA error checks in UpSampleBicubic2d.cu
This will now give more informative errors:

  RuntimeError: CUDA error: too many resources requested for launch

instead of

  RuntimeError: Failed with error code 0